{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "dbd5dc88",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3262e92c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Open excel or xlsx file\n",
    "data=pd.read_excel('C:\\\\Users\\\\pijan_000\\\\Downloads\\\\articles.xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "19883b46",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>article_id</th>\n",
       "      <th>top_article</th>\n",
       "      <th>engagement_reaction_count</th>\n",
       "      <th>engagement_comment_count</th>\n",
       "      <th>engagement_share_count</th>\n",
       "      <th>engagement_comment_plugin_count</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>10437.000000</td>\n",
       "      <td>10435.000000</td>\n",
       "      <td>10319.000000</td>\n",
       "      <td>10319.000000</td>\n",
       "      <td>10319.000000</td>\n",
       "      <td>10319.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>5218.000000</td>\n",
       "      <td>0.122089</td>\n",
       "      <td>381.395290</td>\n",
       "      <td>124.032949</td>\n",
       "      <td>196.236263</td>\n",
       "      <td>0.011629</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>3013.046714</td>\n",
       "      <td>0.327404</td>\n",
       "      <td>4433.344792</td>\n",
       "      <td>965.351188</td>\n",
       "      <td>1020.680229</td>\n",
       "      <td>0.268276</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>2609.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>5218.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>8.000000</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>7827.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>43.000000</td>\n",
       "      <td>12.000000</td>\n",
       "      <td>47.500000</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>10436.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>354132.000000</td>\n",
       "      <td>48490.000000</td>\n",
       "      <td>39422.000000</td>\n",
       "      <td>15.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         article_id   top_article  engagement_reaction_count  \\\n",
       "count  10437.000000  10435.000000               10319.000000   \n",
       "mean    5218.000000      0.122089                 381.395290   \n",
       "std     3013.046714      0.327404                4433.344792   \n",
       "min        0.000000      0.000000                   0.000000   \n",
       "25%     2609.000000      0.000000                   0.000000   \n",
       "50%     5218.000000      0.000000                   1.000000   \n",
       "75%     7827.000000      0.000000                  43.000000   \n",
       "max    10436.000000      1.000000              354132.000000   \n",
       "\n",
       "       engagement_comment_count  engagement_share_count  \\\n",
       "count              10319.000000            10319.000000   \n",
       "mean                 124.032949              196.236263   \n",
       "std                  965.351188             1020.680229   \n",
       "min                    0.000000                0.000000   \n",
       "25%                    0.000000                1.000000   \n",
       "50%                    0.000000                8.000000   \n",
       "75%                   12.000000               47.500000   \n",
       "max                48490.000000            39422.000000   \n",
       "\n",
       "       engagement_comment_plugin_count  \n",
       "count                     10319.000000  \n",
       "mean                          0.011629  \n",
       "std                           0.268276  \n",
       "min                           0.000000  \n",
       "25%                           0.000000  \n",
       "50%                           0.000000  \n",
       "75%                           0.000000  \n",
       "max                          15.000000  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#summary of the data\n",
    "data.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "114f6165",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<bound method DataFrame.info of        article_id           source_id         source_name  \\\n",
       "0               0             reuters             Reuters   \n",
       "1               1     the-irish-times     The Irish Times   \n",
       "2               2     the-irish-times     The Irish Times   \n",
       "3               3  al-jazeera-english  Al Jazeera English   \n",
       "4               4            bbc-news            BBC News   \n",
       "...           ...                 ...                 ...   \n",
       "10432       10432            abc-news            ABC News   \n",
       "10433       10433             reuters             Reuters   \n",
       "10434       10434                 cnn                 CNN   \n",
       "10435       10435            cbs-news            CBS News   \n",
       "10436       10436            cbs-news            CBS News   \n",
       "\n",
       "                       author  \\\n",
       "0           Reuters Editorial   \n",
       "1          Eoin Burke-Kennedy   \n",
       "2           Deirdre McQuillan   \n",
       "3                  Al Jazeera   \n",
       "4                    BBC News   \n",
       "...                       ...   \n",
       "10432    The Associated Press   \n",
       "10433       Sumeet Chatterjee   \n",
       "10434  Lauren M. Johnson, CNN   \n",
       "10435                CBS News   \n",
       "10436                CBS News   \n",
       "\n",
       "                                                   title  \\\n",
       "0      NTSB says Autopilot engaged in 2018 California...   \n",
       "1           Unemployment falls to post-crash low of 5.2%   \n",
       "2      Louise Kennedy AW2019: Long coats, sparkling t...   \n",
       "3      North Korean footballer Han joins Italian gian...   \n",
       "4      UK government lawyer says proroguing parliamen...   \n",
       "...                                                  ...   \n",
       "10432  Drop in US service sector activity raises econ...   \n",
       "10433  Banker defections pose challenge for Credit Su...   \n",
       "10434  A 5-year-old cancer survivor donates 3,000 toy...   \n",
       "10435                                 Fateful Connection   \n",
       "10436                             Love, Hate & Obsession   \n",
       "\n",
       "                                             description  \\\n",
       "0      The National Transportation Safety Board said ...   \n",
       "1      Latest monthly figures reflect continued growt...   \n",
       "2      Autumn-winter collection features designer’s g...   \n",
       "3      Han is the first North Korean player in the Se...   \n",
       "4      The UK government's lawyer, David Johnston arg...   \n",
       "...                                                  ...   \n",
       "10432  Get breaking national and world news, broadcas...   \n",
       "10433  The announcement by Julius Baer this week that...   \n",
       "10434  Weston Newswanger is just a normal 5-year-old ...   \n",
       "10435  A detective is haunted by the case of two wome...   \n",
       "10436  Who wanted one-time millionaire Lanny Horwitz ...   \n",
       "\n",
       "                                                     url  \\\n",
       "0      https://www.reuters.com/article/us-tesla-crash...   \n",
       "1      https://www.irishtimes.com/business/economy/un...   \n",
       "2      https://www.irishtimes.com/\\t\\t\\t\\t\\t\\t\\t/life...   \n",
       "3      https://www.aljazeera.com/news/2019/09/north-k...   \n",
       "4      https://www.bbc.co.uk/news/av/uk-scotland-4956...   \n",
       "...                                                  ...   \n",
       "10432  https://abcnews.go.com/Business/wireStory/drop...   \n",
       "10433  https://www.reuters.com/article/us-credit-suis...   \n",
       "10434  https://www.cnn.com/2019/10/03/us/five-year-ol...   \n",
       "10435  https://www.cbsnews.com/video/fateful-connecti...   \n",
       "10436  https://www.cbsnews.com/video/love-hate-obsess...   \n",
       "\n",
       "                                            url_to_image  \\\n",
       "0      https://s4.reutersmedia.net/resources/r/?m=02&...   \n",
       "1      https://www.irishtimes.com/image-creator/?id=1...   \n",
       "2      https://www.irishtimes.com/image-creator/?id=1...   \n",
       "3      https://www.aljazeera.com/mritems/Images/2019/...   \n",
       "4      https://ichef.bbci.co.uk/news/1024/branded_new...   \n",
       "...                                                  ...   \n",
       "10432  https://s.abcnews.com/images/US/WireAP_eb147c9...   \n",
       "10433  https://s3.reutersmedia.net/resources/r/?m=02&...   \n",
       "10434  https://cdn.cnn.com/cnnnext/dam/assets/1910021...   \n",
       "10435  https://cbsnews1.cbsistatic.com/hub/i/r/2019/1...   \n",
       "10436  https://cbsnews1.cbsistatic.com/hub/i/r/2017/0...   \n",
       "\n",
       "               published_at  \\\n",
       "0      2019-09-03T16:22:20Z   \n",
       "1      2019-09-03T10:32:28Z   \n",
       "2      2019-09-03T14:40:00Z   \n",
       "3      2019-09-03T17:25:39Z   \n",
       "4      2019-09-03T14:39:21Z   \n",
       "...                     ...   \n",
       "10432  2019-10-03T16:30:16Z   \n",
       "10433  2019-10-03T15:59:52Z   \n",
       "10434  2019-10-03T11:20:06Z   \n",
       "10435  2019-10-03T16:40:03Z   \n",
       "10436  2019-10-03T16:35:13Z   \n",
       "\n",
       "                                                 content  top_article  \\\n",
       "0      WASHINGTON (Reuters) - The National Transporta...          0.0   \n",
       "1      The States jobless rate fell to 5.2 per cent l...          0.0   \n",
       "2      Louise Kennedy is showing off her autumn-winte...          1.0   \n",
       "3      Han Kwang Song, the first North Korean footbal...          0.0   \n",
       "4                                                    NaN          0.0   \n",
       "...                                                  ...          ...   \n",
       "10432  Growth in the U.S. economys vast services sect...          0.0   \n",
       "10433  ZURICH/HONG KONG (Reuters) - The announcement ...          0.0   \n",
       "10434                                                NaN          0.0   \n",
       "10435                                                NaN          0.0   \n",
       "10436                                                NaN          0.0   \n",
       "\n",
       "       engagement_reaction_count  engagement_comment_count  \\\n",
       "0                            0.0                       0.0   \n",
       "1                            6.0                      10.0   \n",
       "2                            NaN                       NaN   \n",
       "3                            0.0                       0.0   \n",
       "4                            0.0                       0.0   \n",
       "...                          ...                       ...   \n",
       "10432                        0.0                       0.0   \n",
       "10433                        0.0                       0.0   \n",
       "10434                     4072.0                     179.0   \n",
       "10435                        0.0                       0.0   \n",
       "10436                        0.0                       0.0   \n",
       "\n",
       "       engagement_share_count  engagement_comment_plugin_count  \n",
       "0                      2528.0                              0.0  \n",
       "1                         2.0                              0.0  \n",
       "2                         NaN                              NaN  \n",
       "3                         7.0                              0.0  \n",
       "4                         0.0                              0.0  \n",
       "...                       ...                              ...  \n",
       "10432                     0.0                              0.0  \n",
       "10433                   627.0                              0.0  \n",
       "10434                   466.0                              0.0  \n",
       "10435                     0.0                              0.0  \n",
       "10436                     0.0                              0.0  \n",
       "\n",
       "[10437 rows x 15 columns]>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#summary the columns\n",
    "data.info"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "327509ad",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "source_id\n",
       "1                             1\n",
       "abc-news                   1139\n",
       "al-jazeera-english          499\n",
       "bbc-news                   1242\n",
       "business-insider           1048\n",
       "cbs-news                    952\n",
       "cnn                        1132\n",
       "espn                         82\n",
       "newsweek                    539\n",
       "reuters                    1252\n",
       "the-irish-times            1232\n",
       "the-new-york-times          986\n",
       "the-wall-street-journal     333\n",
       "Name: article_id, dtype: int64"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Counting the number of articles per source\n",
    "data.groupby(['source_id'])['article_id'].count()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b86fa15e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "source_id\n",
       "1                                0.0\n",
       "abc-news                    343779.0\n",
       "al-jazeera-english          140410.0\n",
       "bbc-news                    545396.0\n",
       "business-insider            216545.0\n",
       "cbs-news                    459741.0\n",
       "cnn                        1218206.0\n",
       "espn                             0.0\n",
       "newsweek                     93167.0\n",
       "reuters                      16963.0\n",
       "the-irish-times              26838.0\n",
       "the-new-york-times          790449.0\n",
       "the-wall-street-journal      84124.0\n",
       "Name: engagement_reaction_count, dtype: float64"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Number of reactions by publisher\n",
    "data.groupby(['source_id'])['engagement_reaction_count'].sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a5c8b541",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Dropping useless column\n",
    "data = data.drop('engagement_comment_plugin_count' , axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f493e936",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>article_id</th>\n",
       "      <th>source_id</th>\n",
       "      <th>source_name</th>\n",
       "      <th>author</th>\n",
       "      <th>title</th>\n",
       "      <th>description</th>\n",
       "      <th>url</th>\n",
       "      <th>url_to_image</th>\n",
       "      <th>published_at</th>\n",
       "      <th>content</th>\n",
       "      <th>top_article</th>\n",
       "      <th>engagement_reaction_count</th>\n",
       "      <th>engagement_comment_count</th>\n",
       "      <th>engagement_share_count</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>reuters</td>\n",
       "      <td>Reuters</td>\n",
       "      <td>Reuters Editorial</td>\n",
       "      <td>NTSB says Autopilot engaged in 2018 California...</td>\n",
       "      <td>The National Transportation Safety Board said ...</td>\n",
       "      <td>https://www.reuters.com/article/us-tesla-crash...</td>\n",
       "      <td>https://s4.reutersmedia.net/resources/r/?m=02&amp;...</td>\n",
       "      <td>2019-09-03T16:22:20Z</td>\n",
       "      <td>WASHINGTON (Reuters) - The National Transporta...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2528.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>the-irish-times</td>\n",
       "      <td>The Irish Times</td>\n",
       "      <td>Eoin Burke-Kennedy</td>\n",
       "      <td>Unemployment falls to post-crash low of 5.2%</td>\n",
       "      <td>Latest monthly figures reflect continued growt...</td>\n",
       "      <td>https://www.irishtimes.com/business/economy/un...</td>\n",
       "      <td>https://www.irishtimes.com/image-creator/?id=1...</td>\n",
       "      <td>2019-09-03T10:32:28Z</td>\n",
       "      <td>The States jobless rate fell to 5.2 per cent l...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>the-irish-times</td>\n",
       "      <td>The Irish Times</td>\n",
       "      <td>Deirdre McQuillan</td>\n",
       "      <td>Louise Kennedy AW2019: Long coats, sparkling t...</td>\n",
       "      <td>Autumn-winter collection features designer’s g...</td>\n",
       "      <td>https://www.irishtimes.com/\\t\\t\\t\\t\\t\\t\\t/life...</td>\n",
       "      <td>https://www.irishtimes.com/image-creator/?id=1...</td>\n",
       "      <td>2019-09-03T14:40:00Z</td>\n",
       "      <td>Louise Kennedy is showing off her autumn-winte...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>al-jazeera-english</td>\n",
       "      <td>Al Jazeera English</td>\n",
       "      <td>Al Jazeera</td>\n",
       "      <td>North Korean footballer Han joins Italian gian...</td>\n",
       "      <td>Han is the first North Korean player in the Se...</td>\n",
       "      <td>https://www.aljazeera.com/news/2019/09/north-k...</td>\n",
       "      <td>https://www.aljazeera.com/mritems/Images/2019/...</td>\n",
       "      <td>2019-09-03T17:25:39Z</td>\n",
       "      <td>Han Kwang Song, the first North Korean footbal...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>bbc-news</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>UK government lawyer says proroguing parliamen...</td>\n",
       "      <td>The UK government's lawyer, David Johnston arg...</td>\n",
       "      <td>https://www.bbc.co.uk/news/av/uk-scotland-4956...</td>\n",
       "      <td>https://ichef.bbci.co.uk/news/1024/branded_new...</td>\n",
       "      <td>2019-09-03T14:39:21Z</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   article_id           source_id         source_name              author  \\\n",
       "0           0             reuters             Reuters   Reuters Editorial   \n",
       "1           1     the-irish-times     The Irish Times  Eoin Burke-Kennedy   \n",
       "2           2     the-irish-times     The Irish Times   Deirdre McQuillan   \n",
       "3           3  al-jazeera-english  Al Jazeera English          Al Jazeera   \n",
       "4           4            bbc-news            BBC News            BBC News   \n",
       "\n",
       "                                               title  \\\n",
       "0  NTSB says Autopilot engaged in 2018 California...   \n",
       "1       Unemployment falls to post-crash low of 5.2%   \n",
       "2  Louise Kennedy AW2019: Long coats, sparkling t...   \n",
       "3  North Korean footballer Han joins Italian gian...   \n",
       "4  UK government lawyer says proroguing parliamen...   \n",
       "\n",
       "                                         description  \\\n",
       "0  The National Transportation Safety Board said ...   \n",
       "1  Latest monthly figures reflect continued growt...   \n",
       "2  Autumn-winter collection features designer’s g...   \n",
       "3  Han is the first North Korean player in the Se...   \n",
       "4  The UK government's lawyer, David Johnston arg...   \n",
       "\n",
       "                                                 url  \\\n",
       "0  https://www.reuters.com/article/us-tesla-crash...   \n",
       "1  https://www.irishtimes.com/business/economy/un...   \n",
       "2  https://www.irishtimes.com/\\t\\t\\t\\t\\t\\t\\t/life...   \n",
       "3  https://www.aljazeera.com/news/2019/09/north-k...   \n",
       "4  https://www.bbc.co.uk/news/av/uk-scotland-4956...   \n",
       "\n",
       "                                        url_to_image          published_at  \\\n",
       "0  https://s4.reutersmedia.net/resources/r/?m=02&...  2019-09-03T16:22:20Z   \n",
       "1  https://www.irishtimes.com/image-creator/?id=1...  2019-09-03T10:32:28Z   \n",
       "2  https://www.irishtimes.com/image-creator/?id=1...  2019-09-03T14:40:00Z   \n",
       "3  https://www.aljazeera.com/mritems/Images/2019/...  2019-09-03T17:25:39Z   \n",
       "4  https://ichef.bbci.co.uk/news/1024/branded_new...  2019-09-03T14:39:21Z   \n",
       "\n",
       "                                             content  top_article  \\\n",
       "0  WASHINGTON (Reuters) - The National Transporta...          0.0   \n",
       "1  The States jobless rate fell to 5.2 per cent l...          0.0   \n",
       "2  Louise Kennedy is showing off her autumn-winte...          1.0   \n",
       "3  Han Kwang Song, the first North Korean footbal...          0.0   \n",
       "4                                                NaN          0.0   \n",
       "\n",
       "   engagement_reaction_count  engagement_comment_count  engagement_share_count  \n",
       "0                        0.0                       0.0                  2528.0  \n",
       "1                        6.0                      10.0                     2.0  \n",
       "2                        NaN                       NaN                     NaN  \n",
       "3                        0.0                       0.0                     7.0  \n",
       "4                        0.0                       0.0                     0.0  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "da85f084",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Creating keyword flag\n",
    "keyword = 'crash'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "3b8caa54",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Creating function for finding keyword in an articles titles whitch in return creating a flag column\n",
    "# Try is added to avoid an error when the entity is nan\n",
    "def keywordflag(keyword):\n",
    "    length=len(data)\n",
    "    keyword_flag=[]\n",
    "    for x in range(0,length):\n",
    "        heading=data['title'][x]\n",
    "        try:\n",
    "            if keyword in heading:\n",
    "                flag = 1\n",
    "            else:\n",
    "                flag = 0\n",
    "        except: \n",
    "            flag=0\n",
    "        keyword_flag.append(flag)\n",
    "    return keyword_flag\n",
    "\n",
    "keywordflag = keywordflag('murder')\n",
    "data['keyword_flag']= pd.Series(keywordflag)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "51567d1f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>article_id</th>\n",
       "      <th>source_id</th>\n",
       "      <th>source_name</th>\n",
       "      <th>author</th>\n",
       "      <th>title</th>\n",
       "      <th>description</th>\n",
       "      <th>url</th>\n",
       "      <th>url_to_image</th>\n",
       "      <th>published_at</th>\n",
       "      <th>content</th>\n",
       "      <th>top_article</th>\n",
       "      <th>engagement_reaction_count</th>\n",
       "      <th>engagement_comment_count</th>\n",
       "      <th>engagement_share_count</th>\n",
       "      <th>keyword_flag</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>reuters</td>\n",
       "      <td>Reuters</td>\n",
       "      <td>Reuters Editorial</td>\n",
       "      <td>NTSB says Autopilot engaged in 2018 California...</td>\n",
       "      <td>The National Transportation Safety Board said ...</td>\n",
       "      <td>https://www.reuters.com/article/us-tesla-crash...</td>\n",
       "      <td>https://s4.reutersmedia.net/resources/r/?m=02&amp;...</td>\n",
       "      <td>2019-09-03T16:22:20Z</td>\n",
       "      <td>WASHINGTON (Reuters) - The National Transporta...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2528.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>the-irish-times</td>\n",
       "      <td>The Irish Times</td>\n",
       "      <td>Eoin Burke-Kennedy</td>\n",
       "      <td>Unemployment falls to post-crash low of 5.2%</td>\n",
       "      <td>Latest monthly figures reflect continued growt...</td>\n",
       "      <td>https://www.irishtimes.com/business/economy/un...</td>\n",
       "      <td>https://www.irishtimes.com/image-creator/?id=1...</td>\n",
       "      <td>2019-09-03T10:32:28Z</td>\n",
       "      <td>The States jobless rate fell to 5.2 per cent l...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>the-irish-times</td>\n",
       "      <td>The Irish Times</td>\n",
       "      <td>Deirdre McQuillan</td>\n",
       "      <td>Louise Kennedy AW2019: Long coats, sparkling t...</td>\n",
       "      <td>Autumn-winter collection features designer’s g...</td>\n",
       "      <td>https://www.irishtimes.com/\\t\\t\\t\\t\\t\\t\\t/life...</td>\n",
       "      <td>https://www.irishtimes.com/image-creator/?id=1...</td>\n",
       "      <td>2019-09-03T14:40:00Z</td>\n",
       "      <td>Louise Kennedy is showing off her autumn-winte...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>al-jazeera-english</td>\n",
       "      <td>Al Jazeera English</td>\n",
       "      <td>Al Jazeera</td>\n",
       "      <td>North Korean footballer Han joins Italian gian...</td>\n",
       "      <td>Han is the first North Korean player in the Se...</td>\n",
       "      <td>https://www.aljazeera.com/news/2019/09/north-k...</td>\n",
       "      <td>https://www.aljazeera.com/mritems/Images/2019/...</td>\n",
       "      <td>2019-09-03T17:25:39Z</td>\n",
       "      <td>Han Kwang Song, the first North Korean footbal...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>bbc-news</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>UK government lawyer says proroguing parliamen...</td>\n",
       "      <td>The UK government's lawyer, David Johnston arg...</td>\n",
       "      <td>https://www.bbc.co.uk/news/av/uk-scotland-4956...</td>\n",
       "      <td>https://ichef.bbci.co.uk/news/1024/branded_new...</td>\n",
       "      <td>2019-09-03T14:39:21Z</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>5</td>\n",
       "      <td>abc-news</td>\n",
       "      <td>ABC News</td>\n",
       "      <td>The Associated Press</td>\n",
       "      <td>'This Tender Land' is an affecting story about...</td>\n",
       "      <td>\"This Tender Land\" by William Kent Krueger is ...</td>\n",
       "      <td>https://abcnews.go.com/Entertainment/wireStory...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2019-09-03T15:56:49Z</td>\n",
       "      <td>\"This Tender Land: a Novel\" (Atria Books), by ...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>6</td>\n",
       "      <td>reuters</td>\n",
       "      <td>Reuters</td>\n",
       "      <td>Reuters Editorial</td>\n",
       "      <td>EU wants to see if lawmakers will block Brexit...</td>\n",
       "      <td>The European Union is waiting to see if Britis...</td>\n",
       "      <td>https://www.reuters.com/article/us-britain-eu-...</td>\n",
       "      <td>https://s2.reutersmedia.net/resources/r/?m=02&amp;...</td>\n",
       "      <td>2019-09-03T16:25:41Z</td>\n",
       "      <td>LONDON (Reuters) - The European Union is waiti...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>817.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>7</td>\n",
       "      <td>reuters</td>\n",
       "      <td>Reuters</td>\n",
       "      <td>Reuters Editorial</td>\n",
       "      <td>European third quarter profit outlook improves...</td>\n",
       "      <td>Earnings and revenue expectations for European...</td>\n",
       "      <td>https://www.reuters.com/article/us-europe-stoc...</td>\n",
       "      <td>https://s2.reutersmedia.net/resources/r/?m=02&amp;...</td>\n",
       "      <td>2019-09-03T16:53:48Z</td>\n",
       "      <td>LONDON (Reuters) - Earnings and revenue expect...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>8</td>\n",
       "      <td>bbc-news</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>https://www.facebook.com/bbcnews</td>\n",
       "      <td>How are emotional support animals allowed on f...</td>\n",
       "      <td>There's been support dogs, a support turkey, a...</td>\n",
       "      <td>https://www.bbc.co.uk/news/newsbeat-49564227</td>\n",
       "      <td>https://ichef.bbci.co.uk/news/1024/branded_new...</td>\n",
       "      <td>2019-09-03T16:21:52Z</td>\n",
       "      <td>Image copyrightGetty Images_x000D_\\nYou might ...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>6.0</td>\n",
       "      <td>12.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>9</td>\n",
       "      <td>the-irish-times</td>\n",
       "      <td>The Irish Times</td>\n",
       "      <td>Pat Leahy</td>\n",
       "      <td>Boris Johnson to meet Leo Varadkar in Dublin o...</td>\n",
       "      <td>UK prime minister will meet Taoiseach for talk...</td>\n",
       "      <td>https://www.irishtimes.com/news/politics/boris...</td>\n",
       "      <td>https://www.irishtimes.com/image-creator/?id=1...</td>\n",
       "      <td>2019-09-03T15:04:43Z</td>\n",
       "      <td>The British Prime Minister Boris Johnson is to...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>50.0</td>\n",
       "      <td>77.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>10</td>\n",
       "      <td>al-jazeera-english</td>\n",
       "      <td>Al Jazeera English</td>\n",
       "      <td>Sahar Halaimzai</td>\n",
       "      <td>The Afghan 'peace' deal will not bring peace t...</td>\n",
       "      <td>While rushing to strike an agreement with the ...</td>\n",
       "      <td>https://www.aljazeera.com/indepth/opinion/afgh...</td>\n",
       "      <td>https://www.aljazeera.com/mritems/Images/2019/...</td>\n",
       "      <td>2019-09-03T15:54:56Z</td>\n",
       "      <td>In 2001, The United States government invaded ...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>17.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>20.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>11</td>\n",
       "      <td>the-new-york-times</td>\n",
       "      <td>The New York Times</td>\n",
       "      <td>Ben Rothenberg</td>\n",
       "      <td>Daniil Medvedev Rides a Wave of Hostility at t...</td>\n",
       "      <td>The 23-year-old has advanced to his first Gran...</td>\n",
       "      <td>https://www.nytimes.com/2019/09/03/sports/tenn...</td>\n",
       "      <td>https://static01.nyt.com/images/2019/09/03/spo...</td>\n",
       "      <td>2019-09-03T09:59:38Z</td>\n",
       "      <td>Im satisfied because I made a step forward in ...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>9.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>33.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>12</td>\n",
       "      <td>cnn</td>\n",
       "      <td>CNN</td>\n",
       "      <td>Marianne Garvey, CNN</td>\n",
       "      <td>'Saved by the Bell' just may have a reunion co...</td>\n",
       "      <td>\"Saved by the Bell\" may be coming back.</td>\n",
       "      <td>https://www.cnn.com/2019/09/03/entertainment/s...</td>\n",
       "      <td>https://cdn.cnn.com/cnnnext/dam/assets/1904220...</td>\n",
       "      <td>2019-09-03T12:45:52Z</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>37.0</td>\n",
       "      <td>5.0</td>\n",
       "      <td>43.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>13</td>\n",
       "      <td>reuters</td>\n",
       "      <td>Reuters</td>\n",
       "      <td>Reuters Editorial</td>\n",
       "      <td>Marks &amp; Spencer to be kicked out of FTSE 100 f...</td>\n",
       "      <td>Marks &amp; Spencer will be relegated from London'...</td>\n",
       "      <td>https://www.reuters.com/article/us-m-s-stock-f...</td>\n",
       "      <td>https://s3.reutersmedia.net/resources/r/?m=02&amp;...</td>\n",
       "      <td>2019-09-03T16:51:04Z</td>\n",
       "      <td>LONDON (Reuters) - Marks &amp;amp; Spencer (MKS.L)...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>716.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>14</td>\n",
       "      <td>bbc-news</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Neil Lennon: Celtic manager 'very pleased' wit...</td>\n",
       "      <td>Celtic have had a \"very good\" transfer window ...</td>\n",
       "      <td>https://www.bbc.co.uk/sport/football/49570791</td>\n",
       "      <td>https://ichef.bbci.co.uk/onesport/cps/624/cpsp...</td>\n",
       "      <td>2019-09-03T17:06:05Z</td>\n",
       "      <td>Media playback is not supported on this device...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>15</td>\n",
       "      <td>bbc-news</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>https://www.facebook.com/bbcnews</td>\n",
       "      <td>Putney child murder suspects detained by police</td>\n",
       "      <td>The 15-month-old child suffered a cardiac arre...</td>\n",
       "      <td>https://www.bbc.co.uk/news/uk-england-london-4...</td>\n",
       "      <td>https://ichef.bbci.co.uk/news/1024/branded_new...</td>\n",
       "      <td>2019-09-03T15:49:37Z</td>\n",
       "      <td>A murder inquiry has begun after a child died ...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    article_id           source_id         source_name  \\\n",
       "0            0             reuters             Reuters   \n",
       "1            1     the-irish-times     The Irish Times   \n",
       "2            2     the-irish-times     The Irish Times   \n",
       "3            3  al-jazeera-english  Al Jazeera English   \n",
       "4            4            bbc-news            BBC News   \n",
       "5            5            abc-news            ABC News   \n",
       "6            6             reuters             Reuters   \n",
       "7            7             reuters             Reuters   \n",
       "8            8            bbc-news            BBC News   \n",
       "9            9     the-irish-times     The Irish Times   \n",
       "10          10  al-jazeera-english  Al Jazeera English   \n",
       "11          11  the-new-york-times  The New York Times   \n",
       "12          12                 cnn                 CNN   \n",
       "13          13             reuters             Reuters   \n",
       "14          14            bbc-news            BBC News   \n",
       "15          15            bbc-news            BBC News   \n",
       "\n",
       "                              author  \\\n",
       "0                  Reuters Editorial   \n",
       "1                 Eoin Burke-Kennedy   \n",
       "2                  Deirdre McQuillan   \n",
       "3                         Al Jazeera   \n",
       "4                           BBC News   \n",
       "5               The Associated Press   \n",
       "6                  Reuters Editorial   \n",
       "7                  Reuters Editorial   \n",
       "8   https://www.facebook.com/bbcnews   \n",
       "9                          Pat Leahy   \n",
       "10                   Sahar Halaimzai   \n",
       "11                    Ben Rothenberg   \n",
       "12              Marianne Garvey, CNN   \n",
       "13                 Reuters Editorial   \n",
       "14                               NaN   \n",
       "15  https://www.facebook.com/bbcnews   \n",
       "\n",
       "                                                title  \\\n",
       "0   NTSB says Autopilot engaged in 2018 California...   \n",
       "1        Unemployment falls to post-crash low of 5.2%   \n",
       "2   Louise Kennedy AW2019: Long coats, sparkling t...   \n",
       "3   North Korean footballer Han joins Italian gian...   \n",
       "4   UK government lawyer says proroguing parliamen...   \n",
       "5   'This Tender Land' is an affecting story about...   \n",
       "6   EU wants to see if lawmakers will block Brexit...   \n",
       "7   European third quarter profit outlook improves...   \n",
       "8   How are emotional support animals allowed on f...   \n",
       "9   Boris Johnson to meet Leo Varadkar in Dublin o...   \n",
       "10  The Afghan 'peace' deal will not bring peace t...   \n",
       "11  Daniil Medvedev Rides a Wave of Hostility at t...   \n",
       "12  'Saved by the Bell' just may have a reunion co...   \n",
       "13  Marks & Spencer to be kicked out of FTSE 100 f...   \n",
       "14  Neil Lennon: Celtic manager 'very pleased' wit...   \n",
       "15    Putney child murder suspects detained by police   \n",
       "\n",
       "                                          description  \\\n",
       "0   The National Transportation Safety Board said ...   \n",
       "1   Latest monthly figures reflect continued growt...   \n",
       "2   Autumn-winter collection features designer’s g...   \n",
       "3   Han is the first North Korean player in the Se...   \n",
       "4   The UK government's lawyer, David Johnston arg...   \n",
       "5   \"This Tender Land\" by William Kent Krueger is ...   \n",
       "6   The European Union is waiting to see if Britis...   \n",
       "7   Earnings and revenue expectations for European...   \n",
       "8   There's been support dogs, a support turkey, a...   \n",
       "9   UK prime minister will meet Taoiseach for talk...   \n",
       "10  While rushing to strike an agreement with the ...   \n",
       "11  The 23-year-old has advanced to his first Gran...   \n",
       "12            \"Saved by the Bell\" may be coming back.   \n",
       "13  Marks & Spencer will be relegated from London'...   \n",
       "14  Celtic have had a \"very good\" transfer window ...   \n",
       "15  The 15-month-old child suffered a cardiac arre...   \n",
       "\n",
       "                                                  url  \\\n",
       "0   https://www.reuters.com/article/us-tesla-crash...   \n",
       "1   https://www.irishtimes.com/business/economy/un...   \n",
       "2   https://www.irishtimes.com/\\t\\t\\t\\t\\t\\t\\t/life...   \n",
       "3   https://www.aljazeera.com/news/2019/09/north-k...   \n",
       "4   https://www.bbc.co.uk/news/av/uk-scotland-4956...   \n",
       "5   https://abcnews.go.com/Entertainment/wireStory...   \n",
       "6   https://www.reuters.com/article/us-britain-eu-...   \n",
       "7   https://www.reuters.com/article/us-europe-stoc...   \n",
       "8        https://www.bbc.co.uk/news/newsbeat-49564227   \n",
       "9   https://www.irishtimes.com/news/politics/boris...   \n",
       "10  https://www.aljazeera.com/indepth/opinion/afgh...   \n",
       "11  https://www.nytimes.com/2019/09/03/sports/tenn...   \n",
       "12  https://www.cnn.com/2019/09/03/entertainment/s...   \n",
       "13  https://www.reuters.com/article/us-m-s-stock-f...   \n",
       "14      https://www.bbc.co.uk/sport/football/49570791   \n",
       "15  https://www.bbc.co.uk/news/uk-england-london-4...   \n",
       "\n",
       "                                         url_to_image          published_at  \\\n",
       "0   https://s4.reutersmedia.net/resources/r/?m=02&...  2019-09-03T16:22:20Z   \n",
       "1   https://www.irishtimes.com/image-creator/?id=1...  2019-09-03T10:32:28Z   \n",
       "2   https://www.irishtimes.com/image-creator/?id=1...  2019-09-03T14:40:00Z   \n",
       "3   https://www.aljazeera.com/mritems/Images/2019/...  2019-09-03T17:25:39Z   \n",
       "4   https://ichef.bbci.co.uk/news/1024/branded_new...  2019-09-03T14:39:21Z   \n",
       "5                                                 NaN  2019-09-03T15:56:49Z   \n",
       "6   https://s2.reutersmedia.net/resources/r/?m=02&...  2019-09-03T16:25:41Z   \n",
       "7   https://s2.reutersmedia.net/resources/r/?m=02&...  2019-09-03T16:53:48Z   \n",
       "8   https://ichef.bbci.co.uk/news/1024/branded_new...  2019-09-03T16:21:52Z   \n",
       "9   https://www.irishtimes.com/image-creator/?id=1...  2019-09-03T15:04:43Z   \n",
       "10  https://www.aljazeera.com/mritems/Images/2019/...  2019-09-03T15:54:56Z   \n",
       "11  https://static01.nyt.com/images/2019/09/03/spo...  2019-09-03T09:59:38Z   \n",
       "12  https://cdn.cnn.com/cnnnext/dam/assets/1904220...  2019-09-03T12:45:52Z   \n",
       "13  https://s3.reutersmedia.net/resources/r/?m=02&...  2019-09-03T16:51:04Z   \n",
       "14  https://ichef.bbci.co.uk/onesport/cps/624/cpsp...  2019-09-03T17:06:05Z   \n",
       "15  https://ichef.bbci.co.uk/news/1024/branded_new...  2019-09-03T15:49:37Z   \n",
       "\n",
       "                                              content  top_article  \\\n",
       "0   WASHINGTON (Reuters) - The National Transporta...          0.0   \n",
       "1   The States jobless rate fell to 5.2 per cent l...          0.0   \n",
       "2   Louise Kennedy is showing off her autumn-winte...          1.0   \n",
       "3   Han Kwang Song, the first North Korean footbal...          0.0   \n",
       "4                                                 NaN          0.0   \n",
       "5   \"This Tender Land: a Novel\" (Atria Books), by ...          0.0   \n",
       "6   LONDON (Reuters) - The European Union is waiti...          0.0   \n",
       "7   LONDON (Reuters) - Earnings and revenue expect...          0.0   \n",
       "8   Image copyrightGetty Images_x000D_\\nYou might ...          0.0   \n",
       "9   The British Prime Minister Boris Johnson is to...          0.0   \n",
       "10  In 2001, The United States government invaded ...          0.0   \n",
       "11  Im satisfied because I made a step forward in ...          0.0   \n",
       "12                                                NaN          0.0   \n",
       "13  LONDON (Reuters) - Marks &amp; Spencer (MKS.L)...          0.0   \n",
       "14  Media playback is not supported on this device...          0.0   \n",
       "15  A murder inquiry has begun after a child died ...          0.0   \n",
       "\n",
       "    engagement_reaction_count  engagement_comment_count  \\\n",
       "0                         0.0                       0.0   \n",
       "1                         6.0                      10.0   \n",
       "2                         NaN                       NaN   \n",
       "3                         0.0                       0.0   \n",
       "4                         0.0                       0.0   \n",
       "5                         0.0                       0.0   \n",
       "6                         0.0                       0.0   \n",
       "7                         0.0                       0.0   \n",
       "8                         4.0                       6.0   \n",
       "9                        50.0                      77.0   \n",
       "10                       17.0                       1.0   \n",
       "11                        9.0                       7.0   \n",
       "12                       37.0                       5.0   \n",
       "13                        0.0                       0.0   \n",
       "14                        0.0                       0.0   \n",
       "15                        1.0                       0.0   \n",
       "\n",
       "    engagement_share_count  keyword_flag  \n",
       "0                   2528.0             0  \n",
       "1                      2.0             0  \n",
       "2                      NaN             0  \n",
       "3                      7.0             0  \n",
       "4                      0.0             0  \n",
       "5                      0.0             0  \n",
       "6                    817.0             0  \n",
       "7                      0.0             0  \n",
       "8                     12.0             0  \n",
       "9                      8.0             0  \n",
       "10                    20.0             0  \n",
       "11                    33.0             0  \n",
       "12                    43.0             0  \n",
       "13                   716.0             0  \n",
       "14                     0.0             0  \n",
       "15                     3.0             1  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head(16)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "7b6f6270",
   "metadata": {},
   "outputs": [],
   "source": [
    "##SentimentIntensityAnalyzer\n",
    "sent_int=SentimentIntensityAnalyzer()\n",
    "text = data['title'][15]\n",
    "sent = sent_int.polarity_scores(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "4ee1e469",
   "metadata": {},
   "outputs": [],
   "source": [
    "neg = sent['neg']\n",
    "pos = sent['pos']\n",
    "neu = sent['neu']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "cd480354",
   "metadata": {},
   "outputs": [],
   "source": [
    "title_neg_sentiment = []\n",
    "title_pos_sentiment = []\n",
    "title_neu_sentiment = []\n",
    "\n",
    "length=len(data)\n",
    "\n",
    "for x in range(0, length):\n",
    "    try:\n",
    "        text = data['title'][x]\n",
    "        sent_int=SentimentIntensityAnalyzer()\n",
    "        sent = sent_int.polarity_scores(text)\n",
    "        neg = sent['neg']\n",
    "        pos = sent['pos']\n",
    "        neu = sent['neu']\n",
    "    except:\n",
    "        neg = 0\n",
    "        pos = 0\n",
    "        neu = 0\n",
    "    title_neg_sentiment.append(neg)\n",
    "    title_pos_sentiment.append(pos)\n",
    "    title_neu_sentiment.append(neu)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "0fcfec00",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Changing type to a Series\n",
    "title_neg_sentiment = pd.Series(title_neg_sentiment)\n",
    "title_pos_sentiment = pd.Series(title_pos_sentiment)\n",
    "title_neu_sentiment = pd.Series(title_neu_sentiment)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "ddb7bace",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Adding sentiment values to df data\n",
    "data['title_neg_sentiment']=title_neg_sentiment\n",
    "data['title_pos_sentiment']=title_pos_sentiment\n",
    "data['title_neu_sentiment']=title_neu_sentiment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "2632a67e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>article_id</th>\n",
       "      <th>source_id</th>\n",
       "      <th>source_name</th>\n",
       "      <th>author</th>\n",
       "      <th>title</th>\n",
       "      <th>description</th>\n",
       "      <th>url</th>\n",
       "      <th>url_to_image</th>\n",
       "      <th>published_at</th>\n",
       "      <th>content</th>\n",
       "      <th>top_article</th>\n",
       "      <th>engagement_reaction_count</th>\n",
       "      <th>engagement_comment_count</th>\n",
       "      <th>engagement_share_count</th>\n",
       "      <th>keyword_flag</th>\n",
       "      <th>title_neg_sentiment</th>\n",
       "      <th>title_pos_sentiment</th>\n",
       "      <th>title_neu_sentiment</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>reuters</td>\n",
       "      <td>Reuters</td>\n",
       "      <td>Reuters Editorial</td>\n",
       "      <td>NTSB says Autopilot engaged in 2018 California...</td>\n",
       "      <td>The National Transportation Safety Board said ...</td>\n",
       "      <td>https://www.reuters.com/article/us-tesla-crash...</td>\n",
       "      <td>https://s4.reutersmedia.net/resources/r/?m=02&amp;...</td>\n",
       "      <td>2019-09-03T16:22:20Z</td>\n",
       "      <td>WASHINGTON (Reuters) - The National Transporta...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2528.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.218</td>\n",
       "      <td>0.218</td>\n",
       "      <td>0.565</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>the-irish-times</td>\n",
       "      <td>The Irish Times</td>\n",
       "      <td>Eoin Burke-Kennedy</td>\n",
       "      <td>Unemployment falls to post-crash low of 5.2%</td>\n",
       "      <td>Latest monthly figures reflect continued growt...</td>\n",
       "      <td>https://www.irishtimes.com/business/economy/un...</td>\n",
       "      <td>https://www.irishtimes.com/image-creator/?id=1...</td>\n",
       "      <td>2019-09-03T10:32:28Z</td>\n",
       "      <td>The States jobless rate fell to 5.2 per cent l...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.500</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>the-irish-times</td>\n",
       "      <td>The Irish Times</td>\n",
       "      <td>Deirdre McQuillan</td>\n",
       "      <td>Louise Kennedy AW2019: Long coats, sparkling t...</td>\n",
       "      <td>Autumn-winter collection features designer’s g...</td>\n",
       "      <td>https://www.irishtimes.com/\\t\\t\\t\\t\\t\\t\\t/life...</td>\n",
       "      <td>https://www.irishtimes.com/image-creator/?id=1...</td>\n",
       "      <td>2019-09-03T14:40:00Z</td>\n",
       "      <td>Louise Kennedy is showing off her autumn-winte...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.180</td>\n",
       "      <td>0.820</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>al-jazeera-english</td>\n",
       "      <td>Al Jazeera English</td>\n",
       "      <td>Al Jazeera</td>\n",
       "      <td>North Korean footballer Han joins Italian gian...</td>\n",
       "      <td>Han is the first North Korean player in the Se...</td>\n",
       "      <td>https://www.aljazeera.com/news/2019/09/north-k...</td>\n",
       "      <td>https://www.aljazeera.com/mritems/Images/2019/...</td>\n",
       "      <td>2019-09-03T17:25:39Z</td>\n",
       "      <td>Han Kwang Song, the first North Korean footbal...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.000</td>\n",
       "      <td>1.000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>bbc-news</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>BBC News</td>\n",
       "      <td>UK government lawyer says proroguing parliamen...</td>\n",
       "      <td>The UK government's lawyer, David Johnston arg...</td>\n",
       "      <td>https://www.bbc.co.uk/news/av/uk-scotland-4956...</td>\n",
       "      <td>https://ichef.bbci.co.uk/news/1024/branded_new...</td>\n",
       "      <td>2019-09-03T14:39:21Z</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.146</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.854</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   article_id           source_id         source_name              author  \\\n",
       "0           0             reuters             Reuters   Reuters Editorial   \n",
       "1           1     the-irish-times     The Irish Times  Eoin Burke-Kennedy   \n",
       "2           2     the-irish-times     The Irish Times   Deirdre McQuillan   \n",
       "3           3  al-jazeera-english  Al Jazeera English          Al Jazeera   \n",
       "4           4            bbc-news            BBC News            BBC News   \n",
       "\n",
       "                                               title  \\\n",
       "0  NTSB says Autopilot engaged in 2018 California...   \n",
       "1       Unemployment falls to post-crash low of 5.2%   \n",
       "2  Louise Kennedy AW2019: Long coats, sparkling t...   \n",
       "3  North Korean footballer Han joins Italian gian...   \n",
       "4  UK government lawyer says proroguing parliamen...   \n",
       "\n",
       "                                         description  \\\n",
       "0  The National Transportation Safety Board said ...   \n",
       "1  Latest monthly figures reflect continued growt...   \n",
       "2  Autumn-winter collection features designer’s g...   \n",
       "3  Han is the first North Korean player in the Se...   \n",
       "4  The UK government's lawyer, David Johnston arg...   \n",
       "\n",
       "                                                 url  \\\n",
       "0  https://www.reuters.com/article/us-tesla-crash...   \n",
       "1  https://www.irishtimes.com/business/economy/un...   \n",
       "2  https://www.irishtimes.com/\\t\\t\\t\\t\\t\\t\\t/life...   \n",
       "3  https://www.aljazeera.com/news/2019/09/north-k...   \n",
       "4  https://www.bbc.co.uk/news/av/uk-scotland-4956...   \n",
       "\n",
       "                                        url_to_image          published_at  \\\n",
       "0  https://s4.reutersmedia.net/resources/r/?m=02&...  2019-09-03T16:22:20Z   \n",
       "1  https://www.irishtimes.com/image-creator/?id=1...  2019-09-03T10:32:28Z   \n",
       "2  https://www.irishtimes.com/image-creator/?id=1...  2019-09-03T14:40:00Z   \n",
       "3  https://www.aljazeera.com/mritems/Images/2019/...  2019-09-03T17:25:39Z   \n",
       "4  https://ichef.bbci.co.uk/news/1024/branded_new...  2019-09-03T14:39:21Z   \n",
       "\n",
       "                                             content  top_article  \\\n",
       "0  WASHINGTON (Reuters) - The National Transporta...          0.0   \n",
       "1  The States jobless rate fell to 5.2 per cent l...          0.0   \n",
       "2  Louise Kennedy is showing off her autumn-winte...          1.0   \n",
       "3  Han Kwang Song, the first North Korean footbal...          0.0   \n",
       "4                                                NaN          0.0   \n",
       "\n",
       "   engagement_reaction_count  engagement_comment_count  \\\n",
       "0                        0.0                       0.0   \n",
       "1                        6.0                      10.0   \n",
       "2                        NaN                       NaN   \n",
       "3                        0.0                       0.0   \n",
       "4                        0.0                       0.0   \n",
       "\n",
       "   engagement_share_count  keyword_flag  title_neg_sentiment  \\\n",
       "0                  2528.0             0                0.218   \n",
       "1                     2.0             0                0.500   \n",
       "2                     NaN             0                0.000   \n",
       "3                     7.0             0                0.000   \n",
       "4                     0.0             0                0.146   \n",
       "\n",
       "   title_pos_sentiment  title_neu_sentiment  \n",
       "0                0.218                0.565  \n",
       "1                0.000                0.500  \n",
       "2                0.180                0.820  \n",
       "3                0.000                1.000  \n",
       "4                0.000                0.854  "
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "f6dfa524",
   "metadata": {},
   "outputs": [],
   "source": [
    "#saving table in excel file\n",
    "data.to_excel('blogme_clean.xlsx', sheet_name = 'blogmedata', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c12e4f7f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
